# Generated by Django 5.2.6 on 2025-09-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id_completed',
            new_name='is_completed',
        ),
    ]
